name: Running Code Coverage & Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    name: Build on node ${{ matrix.node-version }} and ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Only node version 15 > validates test.
        node-version: [15.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      # - name: Next build
      #   run: npm run build
      # next build causes error due to mongodb client setup
